"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.vsCodeExtsTemplate = exports.editorConfigTemplate = exports.gitIgnoreTemplate = exports.packageJsonTemplate = exports.tsLintConfigTemplate = exports.tsConfigTemplate = exports.readmeTemplate = exports.mainTemplate = void 0;
const editorConfigTemplate_1 = require("./editorConfigTemplate");
Object.defineProperty(exports, "editorConfigTemplate", { enumerable: true, get: function () { return editorConfigTemplate_1.editorConfigTemplate; } });
const gitIgnoreTemplate_1 = require("./gitIgnoreTemplate");
Object.defineProperty(exports, "gitIgnoreTemplate", { enumerable: true, get: function () { return gitIgnoreTemplate_1.gitIgnoreTemplate; } });
const mainTemplate_1 = require("./mainTemplate");
Object.defineProperty(exports, "mainTemplate", { enumerable: true, get: function () { return mainTemplate_1.mainTemplate; } });
const packageJsonTemplate_1 = require("./packageJsonTemplate");
Object.defineProperty(exports, "packageJsonTemplate", { enumerable: true, get: function () { return packageJsonTemplate_1.packageJsonTemplate; } });
const readmeTemplate_1 = require("./readmeTemplate");
Object.defineProperty(exports, "readmeTemplate", { enumerable: true, get: function () { return readmeTemplate_1.readmeTemplate; } });
const tsConfigTemplate_1 = require("./tsConfigTemplate");
Object.defineProperty(exports, "tsConfigTemplate", { enumerable: true, get: function () { return tsConfigTemplate_1.tsConfigTemplate; } });
const tsLintConfigTemplate_1 = require("./tsLintConfigTemplate");
Object.defineProperty(exports, "tsLintConfigTemplate", { enumerable: true, get: function () { return tsLintConfigTemplate_1.tsLintConfigTemplate; } });
const vsCodeExtsTemplate_1 = require("./vsCodeExtsTemplate");
Object.defineProperty(exports, "vsCodeExtsTemplate", { enumerable: true, get: function () { return vsCodeExtsTemplate_1.vsCodeExtsTemplate; } });
//# sourceMappingURL=index.js.map